

EXPERIMENT_CLASSES = ['fantasy_football','event_quarters']
YEARS = [2022, 2023, 2024]
POSITIONS = ['QB', 'RB', 'TE', 'WR']
TARGET = ['fantasy_points']

POSITION_MAPPER = {'': 'NA',
 'B': 'o_rush',
 'BB': 'o_rush',
 'C': 'o_line',
 'CB': 'd_field',
 'DB': 'd_field',
 'DE': 'd_line',
 'DG': 'd_line',
 'DL': 'd_line',
 'DT': 'd_line',
 'E': 'd_line',
 'EDGE': 'd_line',
 'FB': 'o_rush',
 'FL': 'o_pass',
 'FS': 'd_field',
 'G': 'o_line',
 'HB': 'o_rush',
 'ILB': 'd_field',
 'K': 'kick',
 'KR': 'special_teams',
 'LB': 'd_field',
 'LCB': 'd_field',
 'LDE': 'd_line',
 'LDH': 'o_rush',
 'LDT': 'd_line',
 'LE': 'd_line',
 'LG': 'o_line',
 'LH': 'o_rush',
 'LILB': 'd_field',
 'LLB': 'd_field',
 'LOLB': 'd_field',
 'LOT': 'o_line',
 'LS': 'd_field',
 'LT': 'o_line',
 'MG': 'o_line',
 'MIKE': 'd_field',
 'MLB': 'd_field',
 'NT': 'd_line',
 'OG': 'o_line',
 'OL': 'o_line',
 'OLB': 'd_field',
 'OT': 'o_line',
 'P': 'kick',
 'PR': 'special_teams',
 'QB': 'quarterback',
 'RB': 'o_rush',
 'RCB': 'd_field',
 'RDE': 'd_line',
 'RDH': 'o_rush',
 'RDT': 'd_line',
 'RE': 'd_line',
 'RET': 'special_teams',
 'RG': 'o_line',
 'RH': 'o_rush',
 'RILB': 'd_field',
 'RLB': 'd_field',
 'ROLB': 'd_field',
 'ROT': 'o_line',
 'RS': 'd_field',
 'RT': 'o_line',
 'RUSH': 'd_field',
 'S': 'd_field',
 'SAM': 'd_field',
 'SAF': 'd_field',
 'SE': 'o_pass',
 'SLB': 'd_field',
 'SS': 'd_field',
 'T': 'o_line',
 'TB': 'o_rush',
 'TE': 'o_pass',
 'WB': 'o_rush',
 'WILL': 'd_field',
 'WLB': 'd_field',
 'WR': 'o_pass'}

HIGH_POSITION_MAPPER = {
    'd_line':'def',
    'kick':'st',
    'd_field':'def',
    'o_line':'off',
    'o_pass':'off',
    'o_rush':'off',
    'NA':'NA',
    'quarterback':'off'
}